default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost

development:
  <<: *default
  database: copywriter_app_development

test:
  <<: *default
  database: copywriter_app_test

production:
  <<: *default
  database: copywriter_app_production
  username: copywriter_app
  password: <%= ENV['COPYWRITER_APP_DATABASE_PASSWORD'] %>
